### PR TITLE
Consolidate languages

### PR DESCRIPTION
**Pull request by johenglisch**
Currently the code considers all languages from all contributions separately, resulting in duplicates.  This patch changes the behaviour so that languages with the same glottocode are collapsed into one.

### CODE REVIEW

**Comment by LinguList** [comment]
Are these languages collapsed into one, or rather kept separate and you take the winner by taking the largest list? This is what we do in lexibank-analysed now.

**Comment by johenglisch** [comment]
The code collapses them, i.e. it collects all forms from across all contributions, assigns them to the same glottocode, and drops any duplicate forms.

So, if (as an extreme example) one dataset had all the body parts of a language and one had all the objects, they would both be used to find colexifications.

**Comment by johenglisch** [comment]
>some infrequent colexifications do not appear anymore

Yeah, apparently.  And a few new ones took their place:

    ArmAndMoon
    EarAndBark
    EyeAndButton
    EyebrowAndEdge
    EyelidAndBark
    HairbodyAndLeaf
    HandAndEgg
    HeadAndGourd
    HeartAndStone
    HeelAndBottom
    HeelAndCorner
    LegAndAnthill
    LegAndMoon
    LiverAndJug
    NoseAndMountain
    NoseAndTipofobject
    ShoulderbladeAndRudder
    SkinAndCloud
    SkinhumanAndLeather
    StomachAndMill
    ToothAndSeed
    WaistAndTreetrunk

**Comment by johenglisch** [comment]
Also, here are all the colexifications that *didn't* make it:

    ArmAndValley
    BoneAndBowl
    BoneAndPlate
    EyeAndTree
    ForeheadAndPan
    HandAndMountain
    HandAndValley
    HeadAndCape
    HipAndSide
    LegAndBowl
    LegAndCup
    LungAndLake
    NoseAndArrow
    NoseAndFlower
    NoseAndTop
    NostrilAndHole
    SkinAndLoincloth
    SkinAndMushroom
    TemplesAndTop
    ThroatAndNecklace
    TongueAndFlame
    ToothAndBead

**Comment by AnnikaTjuka** [comment]
Interesting, the new ones are also cool! I would however like to keep cases such as _ti_ in Komi and Udmurt since they are from two language varieties with different Glottocodes spoken in different areas. 

The cases with several dialects in one data set (e.g., Kumyk (Kajtak Tumenler dialect), etc.) are more tricky because the distinction between dialect and language is contestable in the assignment of Glottocodes. But I also don't want to start a philosophical discussion. Would it be possible to keep the _ti_ cases and leave out the Kumyk cases? Or do we have to choose one or the other?

**Comment by AnnikaTjuka** [comment]
One thing, I just noticed. The total number of colexifications, i.e., 93, does not change. Do we need to make the language selection before selecting the colexifications with good coverage?

**Comment by AnnikaTjuka** [comment]
I assume that we have only one gloss mapped to each concept, but there might be some double mappings. Thus, the result in the LUNG-LAKE example would be:

```
forms_by_concept[komi1267, LAKE] == {'ti'}
forms_by_concept[komi1267, LUNG] == {'ti'}
forms_by_concept[udmu1245, LAKE] == {'ti'}
forms_by_concept[udmu1245, LUNG] == {'ti'}
```
should result in
```
colexifications[komi1267, 'ti'] == {LAKE, LUNG}
colexifications[udmu1245, 'ti'] == {LAKE, LUNG}
```

My guess is that @LinguList opted for selecting the largest list as a winner instead of the unique Glottocodes because a) the dialects stay, b) the data from e.g., `clics1-KomiZyrianstd` and `ids-139` are identical since `ids-139` is a subset of CLICS1.

**Comment by johenglisch** [comment]
Okay, I didn't consider the fact that there are datasets that assign the same glottocode to multiple languages in the same language table.

Now, I'm even more confused.  Wasn't the purpose of glottocodes to make languages uniquely identifiable across datasets?  If you can't even identify a language *within* a dataset then yeah, all bets are off.  Like, if the same glottocode appears three times in one dataset and two times in another, then what do you do?

So, I guess that's where the 'largest list' plan comes in, I suppose?  Is the idea that we just count up all forms for a glottocode and compare those across contributions?

    form_count[glottocode] = sum(
        len(language.forms)
        for language in dataset.languages
        if language.glottocode == glottocode)

I.e. if contribution A (e.g. CLICS) has more forms for the glottocode than contribution B (e.g. IDS) we use its dialects (but still separated as individual dialects)?

Or is the idea to drop IDS entirely if it is automagically suspected to be a subset?

(I don't actually know know how lexibank-analysed deals with this -- even though I helped debugging the very line that does it.  Brains are funny like that sometimes.)

**Comment by xrotwang** [comment]
So here's the CLDF view on this: The identifier of a language **within** a dataset is the `ID` in `LanguageTable`. Thus, assigning the same `Glottocode` to multiple languages in the same dataset makes perfect sense, e.g. for a dataset of dialects which don't have dialect-level Glottocodes in Glottolog yet (see https://github.com/lexibank/tppsr/blob/master/cldf/languages.csv).

The purpose of `Glottocode` is **comparability** across datasets. Thus, again, mapping multiple languages in a dataset to the same `Glottocode` makes perfect sense, e.g. if a dataset distinguishes languages based on informant (or in the case above).

**Comment by johenglisch** [comment]
Hm, okay, yeah that makes sense, thanks.

I also had a [quick glance at lexibank-analysed](https://github.com/lexibank/lexibank-analysed/blob/b8317bc146d0cc453740c572abdb7d6d25b7eae0/lexibank_lexibank_analysed.py#L378--L392) and afaict it just loops over all languages with the same glottocode across all contributions and picks the one dialect with the most forms.

From the sound of it that's not what you want, right @AnnikaTjuka?

**Review by AnnikaTjuka — APPROVED** [review]
Many thanks, @johenglisch !

**Pull request merged**
